language: go

go:
  - "1.x"
  - "1.9.x"
  - "1.10.x"
  - master

matrix:
  allow_failures:
    - go: master

go_import_path: go.cryptoscope.co/margaret

install:
  - go get -t -v go.cryptoscope.co/margaret/...
